### ISSUE TITLE
gksu needed as dependency?

### ISSUE THREAD

**Issue by killajoe** [manuel-192/UserManager#1]
![gksu-usermanager](https://user-images.githubusercontent.com/16797647/46255138-bde8ef80-c499-11e8-8233-c79742cdb053.png)
test under KDE/PLASMA

**Comment by manuel-192** [comment]
Yes it is not using gksu. UserManager should be run with root permissions, just as e.g. useradd in CLI.

**Comment by manuel-192** [comment]
> ups sorry... may this was not your app, as the one buildin with plasma has kind of the same name ?
> 
> but:
> 
> `Command 'useradd --create-home --uid 1001 wwweeerr' failed, error code 1 ().` is givin as plasma do not offer sudo app to run graphical apps as root...pkexec is not bring up yad gui (failed to open display) gksu is working

Yes it is not using gksu. UserManager should be run with root permissions, just as e.g. useradd in CLI.
